/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_enrollment_system;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo x270
 */
public class CollegeCourse extends javax.swing.JFrame {
    
//    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(collegeandcourses.class.getName());
    private Framework framework;
    private DefaultTableModel modelCollege;
    private DefaultTableModel modelCourse;
    ImageIcon JOPIcon = new ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmsmalllogo.png"));
    
    public CollegeCourse(Framework framework) {
        this.framework = framework;
        initComponents();
        setTitle("Student Enrollment System");
        modelCollege = (DefaultTableModel) tableCollege.getModel();
        modelCourse = (DefaultTableModel) tableCourse.getModel();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new javax.swing.ButtonGroup();
        semester = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();
        headerHead = new javax.swing.JPanel();
        headerLogoLeft = new javax.swing.JLabel();
        headerTitle = new javax.swing.JLabel();
        headerLogoRight = new javax.swing.JLabel();
        headerButtons = new javax.swing.JPanel();
        buttonStudent = new javax.swing.JButton();
        buttonEnrollment = new javax.swing.JButton();
        buttonFaculty = new javax.swing.JButton();
        buttonSubject = new javax.swing.JButton();
        buttonCollegeCourse = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();
        panelTables = new javax.swing.JPanel();
        scrollTableCollege = new javax.swing.JScrollPane();
        tableCollege = new javax.swing.JTable();
        scrollTableCourse = new javax.swing.JScrollPane();
        tableCourse = new javax.swing.JTable();
        panelFooter = new javax.swing.JPanel();
        footerAdd = new javax.swing.JButton();
        footerModify = new javax.swing.JButton();
        footerDelete = new javax.swing.JButton();

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(255, 255, 204));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelHeader.setForeground(new java.awt.Color(255, 255, 255));
        panelHeader.setLayout(new java.awt.BorderLayout());

        headerHead.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        headerHead.setLayout(new java.awt.GridBagLayout());

        headerLogoLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmsmalllogo.png"))); // NOI18N
        headerLogoLeft.setText(" ");
        headerHead.add(headerLogoLeft, new java.awt.GridBagConstraints());

        headerTitle.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        headerTitle.setText("PAMANTASAN NG LUNGSOD NG MAYNILA");
        headerHead.add(headerTitle, new java.awt.GridBagConstraints());

        headerLogoRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmsmalllogo.png"))); // NOI18N
        headerLogoRight.setText(" ");
        headerHead.add(headerLogoRight, new java.awt.GridBagConstraints());

        panelHeader.add(headerHead, java.awt.BorderLayout.CENTER);

        headerButtons.setLayout(new java.awt.GridLayout(1, 0));

        buttonStudent.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonStudent.setText("Student");
        buttonStudent.addActionListener(this::buttonStudentActionPerformed);
        headerButtons.add(buttonStudent);

        buttonEnrollment.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonEnrollment.setText("Enrollment");
        buttonEnrollment.addActionListener(this::buttonEnrollmentActionPerformed);
        headerButtons.add(buttonEnrollment);

        buttonFaculty.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        buttonFaculty.setText("Faculty");
        buttonFaculty.addActionListener(this::buttonFacultyActionPerformed);
        headerButtons.add(buttonFaculty);

        buttonSubject.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonSubject.setText("Subject");
        buttonSubject.addActionListener(this::buttonSubjectActionPerformed);
        headerButtons.add(buttonSubject);

        buttonCollegeCourse.setBackground(new java.awt.Color(153, 204, 255));
        buttonCollegeCourse.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonCollegeCourse.setText("College & Course");
        buttonCollegeCourse.addActionListener(this::buttonCollegeCourseActionPerformed);
        headerButtons.add(buttonCollegeCourse);

        panelHeader.add(headerButtons, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelHeader, java.awt.BorderLayout.NORTH);
        panelHeader.getAccessibleContext().setAccessibleName("");

        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMain.setLayout(new java.awt.BorderLayout());

        panelTables.setLayout(new java.awt.GridLayout(2, 1));

        scrollTableCollege.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableCollege.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tableCollege.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"BSCS", "Bachelor of Science in Business Administration Major in Human Resource Management", "A"}
            },
            new String [] {
                "College Code", "College Title", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCollege.setPreferredSize(new java.awt.Dimension(1000, 800));
        tableCollege.setShowGrid(true);
        scrollTableCollege.setViewportView(tableCollege);
        if (tableCollege.getColumnModel().getColumnCount() > 0) {
            tableCollege.getColumnModel().getColumn(1).setPreferredWidth(500);
        }

        panelTables.add(scrollTableCollege);

        scrollTableCourse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableCourse.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"BSCS", "CISTM", "College of Information Systems and Technology Management", null}
            },
            new String [] {
                "Program Code", "College Code", "Program Title", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCourse.setPreferredSize(new java.awt.Dimension(1000, 800));
        tableCourse.setShowGrid(false);
        tableCourse.setShowHorizontalLines(true);
        tableCourse.setShowVerticalLines(true);
        scrollTableCourse.setViewportView(tableCourse);
        if (tableCourse.getColumnModel().getColumnCount() > 0) {
            tableCourse.getColumnModel().getColumn(0).setResizable(false);
            tableCourse.getColumnModel().getColumn(2).setPreferredWidth(500);
        }

        panelTables.add(scrollTableCourse);

        panelMain.add(panelTables, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        panelFooter.setLayout(new java.awt.GridLayout(1, 0));

        footerAdd.setBackground(new java.awt.Color(102, 255, 102));
        footerAdd.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        footerAdd.setText("ADD");
        footerAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        footerAdd.addActionListener(this::footerAddActionPerformed);
        panelFooter.add(footerAdd);

        footerModify.setBackground(new java.awt.Color(153, 255, 255));
        footerModify.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        footerModify.setText("MODIFY");
        footerModify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        footerModify.addActionListener(this::footerModifyActionPerformed);
        panelFooter.add(footerModify);

        footerDelete.setBackground(new java.awt.Color(255, 0, 0));
        footerDelete.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        footerDelete.setText("DELETE");
        footerDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        footerDelete.addActionListener(this::footerDeleteActionPerformed);
        panelFooter.add(footerDelete);

        getContentPane().add(panelFooter, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentActionPerformed
        // TODO add your handling code here:
        framework.openStudent();
        this.dispose();
    }//GEN-LAST:event_buttonStudentActionPerformed

    private void buttonSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubjectActionPerformed
        // TODO add your handling code here:
        framework.openSubject();
        this.dispose();
    }//GEN-LAST:event_buttonSubjectActionPerformed

    private void buttonCollegeCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCollegeCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCollegeCourseActionPerformed

    private void footerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footerDeleteActionPerformed
        // TODO add your handling code here:
        int rowCollege = tableCollege.getSelectedRow();
        if (rowCollege >= 0) {
           framework.softDeleteRow("COLLEGE", tableCollege, "college_code");
        }
        else {
           framework.softDeleteRow("CPROGRAM", tableCourse, "program_code");
        }
    }//GEN-LAST:event_footerDeleteActionPerformed

    private void buttonFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacultyActionPerformed
        // TODO add your handling code here:
        framework.openFaculty();
        this.dispose();
    }//GEN-LAST:event_buttonFacultyActionPerformed

    private void footerModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footerModifyActionPerformed
        // TODO add your handling code here:
        int rowCollege = tableCollege.getSelectedRow();
        int rowCourse  = tableCourse.getSelectedRow();
        if (rowCollege >= 0) {
           framework.editSelectedRow("COLLEGE", tableCollege, "college_code");
        }
        else if (rowCourse >= 0) {
           framework.editSelectedRow("CPROGRAM", tableCourse, "program_code");
        }
    }//GEN-LAST:event_footerModifyActionPerformed

    private void buttonEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnrollmentActionPerformed
        // TODO add your handling code here:
        framework.openEnrollment();
        this.dispose();
    }//GEN-LAST:event_buttonEnrollmentActionPerformed

    private void footerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footerAddActionPerformed
        String[] options = { "College", "Course" };
        int choice = JOptionPane.showOptionDialog(
                null,                          // parent component
                "College or Course?",     // message
                "College and Course",              // title
                JOptionPane.YES_NO_OPTION,     // option type
                JOptionPane.QUESTION_MESSAGE,  // message type
                JOPIcon,                        // your ImageIcon
                options,                       // button texts
                options[0]                     // default button
        );
        switch (choice) {
            case 0 -> { framework.addNewRow("COLLEGE");
            }
            case 1 -> { framework.addNewRow("CPROGRAM");
            }
            default -> {
            }
        }
    }//GEN-LAST:event_footerAddActionPerformed
    
    public void clearTable() {
        modelCollege.setRowCount(0);
        modelCourse.setRowCount(0);
    }
    public void loadTable(String code, String title, String status) {
        modelCollege.addRow(new Object[] {code, title, status});
    }
    public void loadTable(String cor, String col, String title, String status) {
        modelCourse.addRow(new Object[] {cor, col, title, status});
    }
//    public void clear
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new collegeandcourses().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCollegeCourse;
    private javax.swing.JButton buttonEnrollment;
    private javax.swing.JButton buttonFaculty;
    private javax.swing.JButton buttonStudent;
    private javax.swing.JButton buttonSubject;
    private javax.swing.JButton footerAdd;
    private javax.swing.JButton footerDelete;
    private javax.swing.JButton footerModify;
    private javax.swing.JPanel headerButtons;
    private javax.swing.JPanel headerHead;
    private javax.swing.JLabel headerLogoLeft;
    private javax.swing.JLabel headerLogoRight;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelTables;
    private javax.swing.JScrollPane scrollTableCollege;
    private javax.swing.JScrollPane scrollTableCourse;
    private javax.swing.ButtonGroup semester;
    private javax.swing.ButtonGroup status;
    private javax.swing.JTable tableCollege;
    private javax.swing.JTable tableCourse;
    // End of variables declaration//GEN-END:variables
}
