/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_enrollment_system;

import java.sql.Date;
import javax.swing.table.DefaultTableModel;

public class Subject extends javax.swing.JFrame {
    
    private Framework framework;
    private DefaultTableModel model;
    public Subject(Framework framework) {
        this.framework = framework;
        initComponents();
        setTitle("Student Enrollment System");
        model = (DefaultTableModel) tableSubject.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new javax.swing.ButtonGroup();
        semester = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();
        headerHead = new javax.swing.JPanel();
        leftlogo = new javax.swing.JLabel();
        schoolName = new javax.swing.JLabel();
        rightlogo = new javax.swing.JLabel();
        headerButtons = new javax.swing.JPanel();
        buttonStudent = new javax.swing.JButton();
        buttonEnrollment = new javax.swing.JButton();
        buttonFaculty = new javax.swing.JButton();
        buttonSubject = new javax.swing.JButton();
        buttonCollegeCourse = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();
        tableSubject = new javax.swing.JTable();
        panelFooter = new javax.swing.JPanel();
        footerAdd = new javax.swing.JButton();
        footerModify = new javax.swing.JButton();
        footerDelete = new javax.swing.JButton();

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(255, 255, 204));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelHeader.setForeground(new java.awt.Color(255, 255, 255));
        panelHeader.setLayout(new java.awt.BorderLayout());

        headerHead.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        headerHead.setLayout(new java.awt.GridBagLayout());

        leftlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmsmalllogo.png"))); // NOI18N
        leftlogo.setText(" ");
        headerHead.add(leftlogo, new java.awt.GridBagConstraints());

        schoolName.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        schoolName.setText("PAMANTASAN NG LUNGSOD NG MAYNILA");
        headerHead.add(schoolName, new java.awt.GridBagConstraints());

        rightlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmsmalllogo.png"))); // NOI18N
        rightlogo.setText(" ");
        headerHead.add(rightlogo, new java.awt.GridBagConstraints());

        panelHeader.add(headerHead, java.awt.BorderLayout.CENTER);

        headerButtons.setLayout(new java.awt.GridLayout(1, 0));

        buttonStudent.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonStudent.setText("Student ");
        buttonStudent.addActionListener(this::buttonStudentActionPerformed);
        headerButtons.add(buttonStudent);

        buttonEnrollment.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonEnrollment.setText("Enrollment");
        buttonEnrollment.addActionListener(this::buttonEnrollmentActionPerformed);
        headerButtons.add(buttonEnrollment);

        buttonFaculty.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        buttonFaculty.setText("Faculty");
        buttonFaculty.addActionListener(this::buttonFacultyActionPerformed);
        headerButtons.add(buttonFaculty);

        buttonSubject.setBackground(new java.awt.Color(153, 204, 255));
        buttonSubject.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonSubject.setText("Subject");
        buttonSubject.addActionListener(this::buttonSubjectActionPerformed);
        headerButtons.add(buttonSubject);

        buttonCollegeCourse.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonCollegeCourse.setText("College & Course");
        buttonCollegeCourse.addActionListener(this::buttonCollegeCourseActionPerformed);
        headerButtons.add(buttonCollegeCourse);

        panelHeader.add(headerButtons, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelHeader, java.awt.BorderLayout.NORTH);
        panelHeader.getAccessibleContext().setAccessibleName("");

        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMain.setLayout(new java.awt.BorderLayout());

        tableSubject.setAutoCreateRowSorter(true);
        tableSubject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableSubject.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tableSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"IPP 0010", "Interdisiplinaryong Pagbasa at Pagsulat Tungo sa Mabisang Pagpapahayag", "2", "CISTM", null, "Alvin Genota", "2024-2025", "1st", null, null, null, null, null, null, null}
            },
            new String [] {
                "Subject Code", "Subject Title", "Units", "College Code", "Professor ID", "Professor", "School Year", "Semester", "Day Schedule", "Start Time", "End TIme", "Room No", "Status", "Date Started", "Date Closed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSubject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableSubject.setPreferredSize(new java.awt.Dimension(1000, 800));
        tableSubject.setShowGrid(true);
        tableSubject.setSurrendersFocusOnKeystroke(true);
        scrollTable.setViewportView(tableSubject);
        if (tableSubject.getColumnModel().getColumnCount() > 0) {
            tableSubject.getColumnModel().getColumn(1).setPreferredWidth(500);
            tableSubject.getColumnModel().getColumn(2).setPreferredWidth(50);
            tableSubject.getColumnModel().getColumn(5).setPreferredWidth(120);
            tableSubject.getColumnModel().getColumn(7).setPreferredWidth(35);
            tableSubject.getColumnModel().getColumn(11).setPreferredWidth(70);
            tableSubject.getColumnModel().getColumn(12).setPreferredWidth(30);
        }

        panelMain.add(scrollTable, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        panelFooter.setLayout(new java.awt.GridLayout(1, 0));

        footerAdd.setBackground(new java.awt.Color(102, 255, 102));
        footerAdd.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        footerAdd.setText("ADD");
        footerAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        footerAdd.addActionListener(this::footerAddActionPerformed);
        panelFooter.add(footerAdd);

        footerModify.setBackground(new java.awt.Color(153, 255, 255));
        footerModify.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        footerModify.setText("MODIFY");
        footerModify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        footerModify.addActionListener(this::footerModifyActionPerformed);
        panelFooter.add(footerModify);

        footerDelete.setBackground(new java.awt.Color(255, 0, 0));
        footerDelete.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        footerDelete.setText("DELETE");
        footerDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        footerDelete.addActionListener(this::footerDeleteActionPerformed);
        panelFooter.add(footerDelete);

        getContentPane().add(panelFooter, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentActionPerformed
        // TODO add your handling code here:
        framework.openStudent();
        this.dispose();
    }//GEN-LAST:event_buttonStudentActionPerformed

    private void buttonSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSubjectActionPerformed

    private void buttonCollegeCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCollegeCourseActionPerformed
        // TODO add your handling code here:
        framework.openCollegeAndCourse();
        this.dispose();
    }//GEN-LAST:event_buttonCollegeCourseActionPerformed

    private void buttonFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacultyActionPerformed
        // TODO add your handling code here:
        framework.openFaculty();
        this.dispose();
    }//GEN-LAST:event_buttonFacultyActionPerformed

    private void footerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footerDeleteActionPerformed
        // TODO add your handling code here:
        framework.softDeleteRow("SUBJECT", tableSubject, "subject_code");
    }//GEN-LAST:event_footerDeleteActionPerformed

    private void buttonEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnrollmentActionPerformed
        // TODO add your handling code here:
        framework.openEnrollment();
        this.dispose();
    }//GEN-LAST:event_buttonEnrollmentActionPerformed

    private void footerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footerAddActionPerformed
        // TODO add your handling code here:
        framework.addNewRow("SUBJECT");
    }//GEN-LAST:event_footerAddActionPerformed

    private void footerModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footerModifyActionPerformed
        // TODO add your handling code here:
        framework.editSelectedRow("SUBJECT", tableSubject, "subject_code");
    }//GEN-LAST:event_footerModifyActionPerformed

    public void clearTable() {
        model.setRowCount(0);
    }
    public void loadTable(String code, String title, String unit, String codeCol, String empid, String empname, String year, String sem, String daysched, String start, String end, String room, String status, Date startdate, Date enddate) {
        model.addRow(new Object[] {code, title, unit, codeCol, empid, empname, year, sem, daysched, start, end, room, status, startdate, enddate});
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new subject_grade().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCollegeCourse;
    private javax.swing.JButton buttonEnrollment;
    private javax.swing.JButton buttonFaculty;
    private javax.swing.JButton buttonStudent;
    private javax.swing.JButton buttonSubject;
    private javax.swing.JButton footerAdd;
    private javax.swing.JButton footerDelete;
    private javax.swing.JButton footerModify;
    private javax.swing.JPanel headerButtons;
    private javax.swing.JPanel headerHead;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel leftlogo;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JLabel rightlogo;
    private javax.swing.JLabel schoolName;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.ButtonGroup semester;
    private javax.swing.ButtonGroup status;
    private javax.swing.JTable tableSubject;
    // End of variables declaration//GEN-END:variables
}
