/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_enrollment_system;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
public class Faculty extends javax.swing.JFrame {
    
    private Framework framework;
    private DefaultTableModel model;
    
    public Faculty(Framework framework) {
        this.framework = framework;
        initComponents();
        setTitle("Student Enrollment System");
        model = (DefaultTableModel) tableFaculty.getModel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new javax.swing.ButtonGroup();
        semester = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();
        headerButtons = new javax.swing.JPanel();
        buttonStudent = new javax.swing.JButton();
        buttonEnrollment = new javax.swing.JButton();
        buttonFaculty = new javax.swing.JButton();
        buttonSubject = new javax.swing.JButton();
        buttonCollegeCourse = new javax.swing.JButton();
        headerHead = new javax.swing.JPanel();
        headerLogoLeft = new javax.swing.JLabel();
        headerTitle = new javax.swing.JLabel();
        headerLogoRight = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();
        tableFaculty = new javax.swing.JTable();
        panelFooter = new javax.swing.JPanel();
        footerAdd = new javax.swing.JButton();
        footerModify = new javax.swing.JButton();
        footerDelete = new javax.swing.JButton();

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(255, 255, 204));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelHeader.setForeground(new java.awt.Color(255, 255, 255));
        panelHeader.setLayout(new java.awt.BorderLayout());

        headerButtons.setLayout(new java.awt.GridLayout(1, 0));

        buttonStudent.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonStudent.setText("Student ");
        buttonStudent.addActionListener(this::buttonStudentActionPerformed);
        headerButtons.add(buttonStudent);

        buttonEnrollment.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonEnrollment.setText("Enrollment");
        buttonEnrollment.addActionListener(this::buttonEnrollmentActionPerformed);
        headerButtons.add(buttonEnrollment);

        buttonFaculty.setBackground(new java.awt.Color(153, 204, 255));
        buttonFaculty.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        buttonFaculty.setText("Faculty");
        buttonFaculty.addActionListener(this::buttonFacultyActionPerformed);
        headerButtons.add(buttonFaculty);

        buttonSubject.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonSubject.setText("Subject");
        buttonSubject.addActionListener(this::buttonSubjectActionPerformed);
        headerButtons.add(buttonSubject);

        buttonCollegeCourse.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonCollegeCourse.setText("College & Course");
        buttonCollegeCourse.addActionListener(this::buttonCollegeCourseActionPerformed);
        headerButtons.add(buttonCollegeCourse);

        panelHeader.add(headerButtons, java.awt.BorderLayout.PAGE_END);

        headerHead.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        headerHead.setLayout(new java.awt.GridBagLayout());

        headerLogoLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmSmallLogo.png"))); // NOI18N
        headerLogoLeft.setText(" ");
        headerHead.add(headerLogoLeft, new java.awt.GridBagConstraints());

        headerTitle.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        headerTitle.setText("PAMANTASAN NG LUNGSOD NG MAYNILA");
        headerHead.add(headerTitle, new java.awt.GridBagConstraints());

        headerLogoRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmSmallLogo.png"))); // NOI18N
        headerLogoRight.setText(" ");
        headerHead.add(headerLogoRight, new java.awt.GridBagConstraints());

        panelHeader.add(headerHead, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelHeader, java.awt.BorderLayout.NORTH);
        panelHeader.getAccessibleContext().setAccessibleName("");

        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMain.setLayout(new java.awt.BorderLayout());

        tableFaculty.setAutoCreateRowSorter(true);
        tableFaculty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableFaculty.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tableFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"EMP 004", "SALGADO, Shirley", "11/24/1989", "F"}
            },
            new String [] {
                "Professor ID", "Professor Name", "Birthday", "Sex"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFaculty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableFaculty.setDragEnabled(true);
        tableFaculty.setPreferredSize(new java.awt.Dimension(1000, 800));
        tableFaculty.setShowGrid(true);
        tableFaculty.setSurrendersFocusOnKeystroke(true);
        scrollTable.setViewportView(tableFaculty);
        if (tableFaculty.getColumnModel().getColumnCount() > 0) {
            tableFaculty.getColumnModel().getColumn(1).setPreferredWidth(500);
        }

        panelMain.add(scrollTable, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        panelFooter.setLayout(new java.awt.GridLayout(1, 0));

        footerAdd.setBackground(new java.awt.Color(102, 255, 102));
        footerAdd.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        footerAdd.setText("ADD");
        footerAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        footerAdd.addActionListener(this::footerAddActionPerformed);
        panelFooter.add(footerAdd);

        footerModify.setBackground(new java.awt.Color(153, 255, 255));
        footerModify.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        footerModify.setText("MODIFY");
        footerModify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        footerModify.addActionListener(this::footerModifyActionPerformed);
        panelFooter.add(footerModify);

        footerDelete.setBackground(new java.awt.Color(255, 0, 0));
        footerDelete.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        footerDelete.setText("DELETE");
        footerDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        footerDelete.addActionListener(this::footerDeleteActionPerformed);
        panelFooter.add(footerDelete);

        getContentPane().add(panelFooter, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentActionPerformed
        // TODO add your handling code here:
        framework.openStudent();
        this.dispose();
    }//GEN-LAST:event_buttonStudentActionPerformed

    private void buttonSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubjectActionPerformed
        // TODO add your handling code here:
        framework.openSubject();
        this.dispose();
    }//GEN-LAST:event_buttonSubjectActionPerformed

    private void buttonCollegeCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCollegeCourseActionPerformed
        // TODO add your handling code here:
        framework.openCollegeAndCourse();
        this.dispose();
    }//GEN-LAST:event_buttonCollegeCourseActionPerformed

    private void footerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footerDeleteActionPerformed
        // TODO add your handling code here:
        framework.softDeleteRow("EMPLOYEE", tableFaculty, "employee_id");
    }//GEN-LAST:event_footerDeleteActionPerformed

    private void buttonFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacultyActionPerformed
        // TODO add your handling code here:
        framework.openFaculty();
        this.dispose();
    }//GEN-LAST:event_buttonFacultyActionPerformed

    private void buttonEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnrollmentActionPerformed
        // TODO add your handling code here:
        framework.openEnrollment();
        this.dispose();
    }//GEN-LAST:event_buttonEnrollmentActionPerformed

    private void footerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footerAddActionPerformed
        // TODO add your handling code here:
        framework.addNewRow("EMPLOYEE");
    }//GEN-LAST:event_footerAddActionPerformed

    private void footerModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footerModifyActionPerformed
        // TODO add your handling code here:
        framework.editSelectedRow("EMPLOYEE", tableFaculty, "employee_id");
    }//GEN-LAST:event_footerModifyActionPerformed
    
    public void clearTable() {
        model.setRowCount(0);
    }
    public void loadTable(String id, String name, Date birthday, String gender) {
        model.addRow(new Object[] {id, name, birthday, gender});
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new faculty_profs_employee().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCollegeCourse;
    private javax.swing.JButton buttonEnrollment;
    private javax.swing.JButton buttonFaculty;
    private javax.swing.JButton buttonStudent;
    private javax.swing.JButton buttonSubject;
    private javax.swing.JButton footerAdd;
    private javax.swing.JButton footerDelete;
    private javax.swing.JButton footerModify;
    private javax.swing.JPanel headerButtons;
    private javax.swing.JPanel headerHead;
    private javax.swing.JLabel headerLogoLeft;
    private javax.swing.JLabel headerLogoRight;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.ButtonGroup semester;
    private javax.swing.ButtonGroup status;
    private javax.swing.JTable tableFaculty;
    // End of variables declaration//GEN-END:variables
}
