/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_enrollment_system;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        LogIn = new javax.swing.JPanel();
        UniveristyName = new javax.swing.JLabel();
        UniveristyName1 = new javax.swing.JLabel();
        UNPW = new javax.swing.JPanel();
        Password = new javax.swing.JLabel();
        User_name = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        Username = new javax.swing.JTextField();
        LOGIN = new javax.swing.JButton();
        UniveristyName2 = new javax.swing.JLabel();
        PLM = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(null);

        LogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LogIn.setOpaque(false);
        LogIn.setLayout(new java.awt.GridBagLayout());

        UniveristyName.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        UniveristyName.setText("PAMANTASAN NG LUNGSOD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 62, 0, 0);
        LogIn.add(UniveristyName, gridBagConstraints);

        UniveristyName1.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        UniveristyName1.setText("NG MAYNILA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 119, 0, 0);
        LogIn.add(UniveristyName1, gridBagConstraints);

        UNPW.setOpaque(false);

        Password.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        Password.setText("Password");

        User_name.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        User_name.setText("Username");

        jPasswordField1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField1.addActionListener(this::jPasswordField1ActionPerformed);

        Username.addActionListener(this::UsernameActionPerformed);

        LOGIN.setBackground(new java.awt.Color(102, 204, 255));
        LOGIN.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        LOGIN.setText("LOGIN");
        LOGIN.addActionListener(this::LOGINActionPerformed);

        javax.swing.GroupLayout UNPWLayout = new javax.swing.GroupLayout(UNPW);
        UNPW.setLayout(UNPWLayout);
        UNPWLayout.setHorizontalGroup(
            UNPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UNPWLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UNPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField1)
                    .addComponent(Username)))
            .addGroup(UNPWLayout.createSequentialGroup()
                .addGroup(UNPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UNPWLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(User_name))
                    .addGroup(UNPWLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Password))
                    .addGroup(UNPWLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 84, Short.MAX_VALUE))
        );
        UNPWLayout.setVerticalGroup(
            UNPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UNPWLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(User_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.ipady = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 39, 23, 40);
        LogIn.add(UNPW, gridBagConstraints);

        UniveristyName2.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        UniveristyName2.setText("LOGIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 141, 0, 0);
        LogIn.add(UniveristyName2, gridBagConstraints);

        bg.add(LogIn);
        LogIn.setBounds(640, 130, 370, 450);

        PLM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/loginbg.jpg"))); // NOI18N
        bg.add(PLM);
        PLM.setBounds(640, 130, 370, 447);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmbg_1 (1).png"))); // NOI18N
        bg.add(jLabel1);
        jLabel1.setBounds(-20, 0, 1570, 896);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGIN;
    private javax.swing.JPanel LogIn;
    private javax.swing.JLabel PLM;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel UNPW;
    private javax.swing.JLabel UniveristyName;
    private javax.swing.JLabel UniveristyName1;
    private javax.swing.JLabel UniveristyName2;
    private javax.swing.JLabel User_name;
    private javax.swing.JTextField Username;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
