/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_enrollment_system;

import java.sql.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo x270
 */
public class subject_grade extends javax.swing.JFrame {
    
//    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(subject_grade.class.getName());
    private Framework framework;
    private DefaultTableModel model;
    public subject_grade(Framework framework) {
        this.framework = framework;
        initComponents();
        model = (DefaultTableModel) subjectTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new javax.swing.ButtonGroup();
        semester = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        buttons = new javax.swing.JPanel();
        studentButton = new javax.swing.JButton();
        enrollmentButton = new javax.swing.JButton();
        facultyButton = new javax.swing.JButton();
        subject_gradeButton = new javax.swing.JButton();
        college_courseButton = new javax.swing.JButton();
        school_name = new javax.swing.JPanel();
        leftlogo = new javax.swing.JLabel();
        schoolName = new javax.swing.JLabel();
        rightlogo = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        add_modify_deleteButtons = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        mainContentPanel = new javax.swing.JPanel();
        TablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectTable = new javax.swing.JTable();

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(255, 255, 204));
        headerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        headerPanel.setForeground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(new java.awt.BorderLayout());

        buttons.setLayout(new java.awt.GridLayout(1, 0));

        studentButton.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        studentButton.setText("Student ");
        studentButton.addActionListener(this::studentButtonActionPerformed);
        buttons.add(studentButton);

        enrollmentButton.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        enrollmentButton.setText("Enrollment");
        enrollmentButton.addActionListener(this::enrollmentButtonActionPerformed);
        buttons.add(enrollmentButton);

        facultyButton.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        facultyButton.setText("Faculty");
        facultyButton.addActionListener(this::facultyButtonActionPerformed);
        buttons.add(facultyButton);

        subject_gradeButton.setBackground(new java.awt.Color(153, 204, 255));
        subject_gradeButton.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        subject_gradeButton.setText("Subject");
        subject_gradeButton.addActionListener(this::subject_gradeButtonActionPerformed);
        buttons.add(subject_gradeButton);

        college_courseButton.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        college_courseButton.setText("College & Course");
        college_courseButton.addActionListener(this::college_courseButtonActionPerformed);
        buttons.add(college_courseButton);

        headerPanel.add(buttons, java.awt.BorderLayout.PAGE_END);

        school_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        school_name.setLayout(new java.awt.GridBagLayout());

        leftlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmsmalllogo.png"))); // NOI18N
        leftlogo.setText(" ");
        school_name.add(leftlogo, new java.awt.GridBagConstraints());

        schoolName.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        schoolName.setText("PAMANTASAN NG LUNGSOD NG MAYNILA");
        school_name.add(schoolName, new java.awt.GridBagConstraints());

        rightlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmsmalllogo.png"))); // NOI18N
        rightlogo.setText(" ");
        school_name.add(rightlogo, new java.awt.GridBagConstraints());

        headerPanel.add(school_name, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);
        headerPanel.getAccessibleContext().setAccessibleName("");

        footerPanel.setLayout(new java.awt.GridLayout(1, 0));

        add_modify_deleteButtons.setLayout(new java.awt.GridLayout(1, 0));

        jButton6.setBackground(new java.awt.Color(102, 255, 102));
        jButton6.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jButton6.setText("ADD");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.addActionListener(this::jButton6ActionPerformed);
        add_modify_deleteButtons.add(jButton6);

        jButton7.setBackground(new java.awt.Color(153, 255, 255));
        jButton7.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jButton7.setText("MODIFY");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.addActionListener(this::jButton7ActionPerformed);
        add_modify_deleteButtons.add(jButton7);

        jButton8.setBackground(new java.awt.Color(255, 0, 0));
        jButton8.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jButton8.setText("DELETE");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton8.addActionListener(this::jButton8ActionPerformed);
        add_modify_deleteButtons.add(jButton8);

        footerPanel.add(add_modify_deleteButtons);

        getContentPane().add(footerPanel, java.awt.BorderLayout.PAGE_END);

        mainContentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainContentPanel.setLayout(new java.awt.BorderLayout());

        TablePanel.setLayout(new java.awt.BorderLayout());

        subjectTable.setAutoCreateRowSorter(true);
        subjectTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        subjectTable.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        subjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"IPP 0010", "Interdisiplinaryong Pagbasa at Pagsulat Tungo sa Mabisang Pagpapahayag", "2", "CISTM", null, "Alvin Genota", "2024-2025", "1st", null, null, null, null, null, null, null}
            },
            new String [] {
                "Subject Code", "Subject Title", "Units", "College Code", "Professor ID", "Professor", "School Year", "Semester", "Day Schedule", "Start Time", "End TIme", "Room No", "Status", "Date Started", "Date Closed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        subjectTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subjectTable.setPreferredSize(new java.awt.Dimension(1000, 800));
        subjectTable.setShowGrid(true);
        subjectTable.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(subjectTable);
        if (subjectTable.getColumnModel().getColumnCount() > 0) {
            subjectTable.getColumnModel().getColumn(1).setPreferredWidth(500);
            subjectTable.getColumnModel().getColumn(2).setPreferredWidth(50);
            subjectTable.getColumnModel().getColumn(5).setPreferredWidth(120);
            subjectTable.getColumnModel().getColumn(7).setPreferredWidth(35);
            subjectTable.getColumnModel().getColumn(11).setPreferredWidth(70);
            subjectTable.getColumnModel().getColumn(12).setPreferredWidth(30);
        }

        TablePanel.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        mainContentPanel.add(TablePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        // TODO add your handling code here:
        framework.openStudent();
        this.dispose();
    }//GEN-LAST:event_studentButtonActionPerformed

    private void subject_gradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject_gradeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject_gradeButtonActionPerformed

    private void college_courseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_college_courseButtonActionPerformed
        // TODO add your handling code here:
        framework.openCollegeAndCourse();
        this.dispose();
    }//GEN-LAST:event_college_courseButtonActionPerformed

    private void facultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyButtonActionPerformed
        // TODO add your handling code here:
        framework.openFaculty();
        this.dispose();
    }//GEN-LAST:event_facultyButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        framework.softDeleteRow("SUBJECT", subjectTable, "subject_code");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void enrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentButtonActionPerformed
        // TODO add your handling code here:
        framework.openEnrollment();
        this.dispose();
    }//GEN-LAST:event_enrollmentButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        framework.addNewRow("SUBJECT");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        framework.editSelectedRow("SUBJECT", subjectTable, "subject_code");
    }//GEN-LAST:event_jButton7ActionPerformed

    public void clearTable() {
        model.setRowCount(0);
    }
    public void loadTable(String code, String title, String unit, String codeCol, String empid, String empname, String year, String sem, String daysched, String start, String end, String room, String status, Date startdate, Date enddate) {
        model.addRow(new Object[] {code, title, unit, codeCol, empid, empname, year, sem, daysched, start, end, room, status, startdate, enddate});
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new subject_grade().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TablePanel;
    private javax.swing.JPanel add_modify_deleteButtons;
    private javax.swing.JPanel buttons;
    private javax.swing.JButton college_courseButton;
    private javax.swing.JButton enrollmentButton;
    private javax.swing.JButton facultyButton;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leftlogo;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JLabel rightlogo;
    private javax.swing.JLabel schoolName;
    private javax.swing.JPanel school_name;
    private javax.swing.ButtonGroup semester;
    private javax.swing.ButtonGroup status;
    private javax.swing.JButton studentButton;
    private javax.swing.JTable subjectTable;
    private javax.swing.JButton subject_gradeButton;
    // End of variables declaration//GEN-END:variables
}
