/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_enrollment_system;

/**
 *
 * @author Lenovo x270
 */
public class ViewGradesColumn_Troi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewGradesColumn_Troi.class.getName());

    /**
     * Creates new form homePage
     */
    public ViewGradesColumn_Troi() {
        initComponents();
        student_names.insertItemAt("", 0);
        student_names.setSelectedIndex(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        status = new javax.swing.ButtonGroup();
        semester = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        school_name = new javax.swing.JPanel();
        leftlogo = new javax.swing.JLabel();
        schoolName = new javax.swing.JLabel();
        rightlogo = new javax.swing.JLabel();
        buttons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        mainContentPanel = new javax.swing.JPanel();
        studentInfoWindow = new javax.swing.JPanel();
        studentInfoandIcon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        studentData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spacer = new javax.swing.JLabel();
        spacer2 = new javax.swing.JLabel();
        yearLevel = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        LEGENDS = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        student_names = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        scheduleCard = new javax.swing.JPanel();
        basicInfoText = new javax.swing.JLabel();
        studentData1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/defaulticon.png"))); // NOI18N
        icon.setFocusable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(255, 255, 204));
        headerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        headerPanel.setForeground(new java.awt.Color(255, 255, 255));
        headerPanel.setLayout(new java.awt.BorderLayout());

        school_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        school_name.setLayout(new java.awt.GridBagLayout());

        leftlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmsmalllogo.png"))); // NOI18N
        leftlogo.setText(" ");
        school_name.add(leftlogo, new java.awt.GridBagConstraints());

        schoolName.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        schoolName.setText("PAMANTASAN NG LUNGSOD NG MAYNILA");
        school_name.add(schoolName, new java.awt.GridBagConstraints());

        rightlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/student_enrollment_system/images/plmsmalllogo.png"))); // NOI18N
        rightlogo.setText(" ");
        school_name.add(rightlogo, new java.awt.GridBagConstraints());

        headerPanel.add(school_name, java.awt.BorderLayout.CENTER);

        buttons.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        buttons.add(jButton1);

        jButton2.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jButton2.setText("Schedule");
        buttons.add(jButton2);

        jButton3.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jButton3.setText("Enrollment");
        buttons.add(jButton3);

        jButton9.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jButton9.setText("View Grade");
        jButton9.addActionListener(this::jButton9ActionPerformed);
        buttons.add(jButton9);

        headerPanel.add(buttons, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);
        headerPanel.getAccessibleContext().setAccessibleName("");

        mainContentPanel.setLayout(new java.awt.BorderLayout());

        studentInfoWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        studentInfoWindow.setOpaque(false);
        studentInfoWindow.setPreferredSize(new java.awt.Dimension(455, 100));
        studentInfoWindow.setRequestFocusEnabled(false);
        studentInfoWindow.setLayout(new java.awt.BorderLayout());

        studentInfoandIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 5, 1));
        studentInfoandIcon.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        studentInfoandIcon.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Information:");
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 90);
        studentInfoandIcon.add(jLabel2, gridBagConstraints);

        studentInfoWindow.add(studentInfoandIcon, java.awt.BorderLayout.NORTH);

        studentData.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 10, 10));
        studentData.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setText("Student Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 30, 0);
        studentData.add(jLabel1, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel4.setText("Block:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 30, 0);
        studentData.add(jLabel4, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setText("Semester:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 30, 0);
        studentData.add(jLabel6, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel8.setText("School Year:");
        jLabel8.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 30, 0);
        studentData.add(jLabel8, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel10.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 30, 0);
        studentData.add(jLabel10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        studentData.add(spacer, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        studentData.add(spacer2, gridBagConstraints);

        yearLevel.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        yearLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select School Year-", "2024 - 2025", "2023 - 2024", "2022 - 2023", "Veterans", " " }));
        yearLevel.addActionListener(this::yearLevelActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 35, 25);
        studentData.add(yearLevel, gridBagConstraints);
        yearLevel.getAccessibleContext().setAccessibleName("");

        status.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jRadioButton1.setText("Regular");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(-30, 0, 0, 135);
        studentData.add(jRadioButton1, gridBagConstraints);

        status.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jRadioButton2.setText("Irregular");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(-35, 120, 0, 70);
        studentData.add(jRadioButton2, gridBagConstraints);

        status.add(LEGENDS);
        LEGENDS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LEGENDS.setForeground(new java.awt.Color(255, 215, 0));
        LEGENDS.setText("Legends");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(-80, 0, 0, 150);
        studentData.add(LEGENDS, gridBagConstraints);

        jComboBox1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jComboBox1.setMaximumRowCount(2);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Block-", "Block 1", "Block 2", "Block 3", "Block 4", "Block 5", "Block 6" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 30, 140);
        studentData.add(jComboBox1, gridBagConstraints);

        semester.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jRadioButton4.setText("1st Sem");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 210);
        studentData.add(jRadioButton4, gridBagConstraints);

        semester.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jRadioButton5.setText("2nd Sem");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(-25, 20, 0, 20);
        studentData.add(jRadioButton5, gridBagConstraints);

        semester.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jRadioButton6.setText("Summer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 0, 0);
        studentData.add(jRadioButton6, gridBagConstraints);

        student_names.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        student_names.setMaximumRowCount(5);
        student_names.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Student-", "Cyrus Kent B. De Guzman", "John Devonaire L. Garcia", "Nheil Jewel F. Blanche", "Troi Isaac V. Limin", "JP \"The Legend\" Medalla", "Curien Del Rosario", "Lorejane Dela Cruz", " " }));
        student_names.addActionListener(this::student_namesActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        studentData.add(student_names, gridBagConstraints);

        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        searchButton.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, -200, 50, 0);
        studentData.add(searchButton, gridBagConstraints);

        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clearButton.setText("Clear");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 50, 0);
        studentData.add(clearButton, gridBagConstraints);

        studentInfoWindow.add(studentData, java.awt.BorderLayout.CENTER);

        mainContentPanel.add(studentInfoWindow, java.awt.BorderLayout.WEST);

        scheduleCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scheduleCard.setForeground(new java.awt.Color(255, 255, 255));
        scheduleCard.setLayout(new java.awt.BorderLayout());

        basicInfoText.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        basicInfoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        basicInfoText.setText("Remark");
        basicInfoText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        basicInfoText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        basicInfoText.setPreferredSize(new java.awt.Dimension(150, 50));
        basicInfoText.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        scheduleCard.add(basicInfoText, java.awt.BorderLayout.NORTH);
        basicInfoText.getAccessibleContext().setAccessibleParent(null);

        studentData1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 10, 10));
        studentData1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 230));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Data Structures and Algorithms (Lec)", "ICC-121-3",  new Integer(3),  new Float(1.75), null, "Passed"},
                {"National Service Program (ROTC)", "NSTP-1",  new Integer(2),  new Float(1.0), null, "Passed"},
                {"Discrete Structures (Lec)", "ICC-212-1",  new Integer(3),  new Float(1.25), null, "Passed"},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"", null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Subject Title", "Subject Code", "Units", "Grade", "Completion Grade", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setMinimumSize(new java.awt.Dimension(75, 140));
        jTable1.setPreferredSize(new java.awt.Dimension(150, 250));
        jTable1.setRequestFocusEnabled(false);
        jTable1.setRowHeight(35);
        jTable1.setRowMargin(10);
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setShowGrid(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        studentData1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(10, 100));

        jLabel3.setText("------------------------ No Entry Follows -------------------------------------------");

        jLabel5.setText("GWA: ( Note: Float value (3,2) )");

        jButton8.setBackground(new java.awt.Color(255, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Delete");
        jButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jButton6.setBackground(new java.awt.Color(102, 255, 102));
        jButton6.setText("Insert");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton7.setBackground(new java.awt.Color(102, 255, 204));
        jButton7.setText("Update");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5)
                        .addGap(123, 123, 123)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton8)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        studentData1.add(jPanel3, java.awt.BorderLayout.PAGE_END);
        studentData1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        scheduleCard.add(studentData1, java.awt.BorderLayout.CENTER);

        mainContentPanel.add(scheduleCard, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void student_namesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_namesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_namesActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void yearLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearLevelActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewGradesColumn_Troi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton LEGENDS;
    private javax.swing.JLabel basicInfoText;
    private javax.swing.JPanel buttons;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel leftlogo;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JLabel rightlogo;
    private javax.swing.JPanel scheduleCard;
    private javax.swing.JLabel schoolName;
    private javax.swing.JPanel school_name;
    private javax.swing.JButton searchButton;
    private javax.swing.ButtonGroup semester;
    private javax.swing.JLabel spacer;
    private javax.swing.JLabel spacer2;
    private javax.swing.ButtonGroup status;
    private javax.swing.JPanel studentData;
    private javax.swing.JPanel studentData1;
    private javax.swing.JPanel studentInfoWindow;
    private javax.swing.JPanel studentInfoandIcon;
    private javax.swing.JComboBox<String> student_names;
    private javax.swing.JComboBox<String> yearLevel;
    // End of variables declaration//GEN-END:variables
}
